---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: arm


steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: REG_NAME
    password: 
      from_secret: REG_PASSWORD
    repo: bboysoul/drone-ddnotice
    registry: docker.io
    tags:
      - latest
      - v1.0.10